### PR TITLE
sgt-puzzles: bump to version 20210409

### PR DESCRIPTION
**Pull request by jslick**
Couple of notes:
* Simon switched to cmake
* There are now .desktop files in the manifest!
  - I'm still too lazy to figure out icons though

## Description of package

Simon Tatham's Portable Puzzle Collection

## Installed manifest of package

(`kiss manifest <pkg>`)

```
/var/db/kiss/installed/sgt-puzzles/version
/var/db/kiss/installed/sgt-puzzles/sources
/var/db/kiss/installed/sgt-puzzles/manifest
/var/db/kiss/installed/sgt-puzzles/depends
/var/db/kiss/installed/sgt-puzzles/checksums
/var/db/kiss/installed/sgt-puzzles/build
/var/db/kiss/installed/sgt-puzzles/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/pixmaps/
/usr/share/applications/sgt-untangle.desktop
/usr/share/applications/sgt-unruly.desktop
/usr/share/applications/sgt-unequal.desktop
/usr/share/applications/sgt-undead.desktop
/usr/share/applications/sgt-twiddle.desktop
/usr/share/applications/sgt-tracks.desktop
/usr/share/applications/sgt-towers.desktop
/usr/share/applications/sgt-tents.desktop
/usr/share/applications/sgt-solo.desktop
/usr/share/applications/sgt-slant.desktop
/usr/share/applications/sgt-sixteen.desktop
/usr/share/applications/sgt-singles.desktop
/usr/share/applications/sgt-signpost.desktop
/usr/share/applications/sgt-samegame.desktop
/usr/share/applications/sgt-rect.desktop
/usr/share/applications/sgt-range.desktop
/usr/share/applications/sgt-pegs.desktop
/usr/share/applications/sgt-pearl.desktop
/usr/share/applications/sgt-pattern.desktop
/usr/share/applications/sgt-palisade.desktop
/usr/share/applications/sgt-netslide.desktop
/usr/share/applications/sgt-net.desktop
/usr/share/applications/sgt-mines.desktop
/usr/share/applications/sgt-map.desktop
/usr/share/applications/sgt-magnets.desktop
/usr/share/applications/sgt-loopy.desktop
/usr/share/applications/sgt-lightup.desktop
/usr/share/applications/sgt-keen.desktop
/usr/share/applications/sgt-inertia.desktop
/usr/share/applications/sgt-guess.desktop
/usr/share/applications/sgt-galaxies.desktop
/usr/share/applications/sgt-flood.desktop
/usr/share/applications/sgt-flip.desktop
/usr/share/applications/sgt-filling.desktop
/usr/share/applications/sgt-fifteen.desktop
/usr/share/applications/sgt-dominosa.desktop
/usr/share/applications/sgt-cube.desktop
/usr/share/applications/sgt-bridges.desktop
/usr/share/applications/sgt-blackbox.desktop
/usr/share/applications/
/usr/share/
/usr/bin/sgt-untangle
/usr/bin/sgt-unruly
/usr/bin/sgt-unequal
/usr/bin/sgt-undead
/usr/bin/sgt-twiddle
/usr/bin/sgt-tracks
/usr/bin/sgt-towers
/usr/bin/sgt-tents
/usr/bin/sgt-solo
/usr/bin/sgt-slant
/usr/bin/sgt-sixteen
/usr/bin/sgt-singles
/usr/bin/sgt-signpost
/usr/bin/sgt-samegame
/usr/bin/sgt-rect
/usr/bin/sgt-range
/usr/bin/sgt-pegs
/usr/bin/sgt-pearl
/usr/bin/sgt-pattern
/usr/bin/sgt-palisade
/usr/bin/sgt-netslide
/usr/bin/sgt-net
/usr/bin/sgt-mines
/usr/bin/sgt-map
/usr/bin/sgt-magnets
/usr/bin/sgt-loopy
/usr/bin/sgt-lightup
/usr/bin/sgt-keen
/usr/bin/sgt-inertia
/usr/bin/sgt-guess
/usr/bin/sgt-galaxies
/usr/bin/sgt-flood
/usr/bin/sgt-flip
/usr/bin/sgt-filling
/usr/bin/sgt-fifteen
/usr/bin/sgt-dominosa
/usr/bin/sgt-cube
/usr/bin/sgt-bridges
/usr/bin/sgt-blackbox
/usr/bin/
/usr/
```

## Existing package

- [X] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
You'll want to add `cmake make` to `depends`.

I have no idea what the source tree looks like, but icons generally go in `/usr/share/icons` - if you'd like to do it. I'm not sure how much it matters.

**Comment by jslick** [comment]
Added `cmake depends`.  Forgot about that.

**Comment by dilyn-corner** [comment]
`sed -i 's/cmake depends/cmake make/' sgt-puzzles/depends` ;)

**Comment by jslick** [comment]
oops, I was in a hurry to play slay the spire and wasn't paying attention.  I'll fix it when I get back to my kisslinux laptop.

**Pull request merged**
