### PR TITLE
drop

### PR DESCRIPTION
**Pull request by git-bruh**
need to check revdeps and stuff

### CODE REVIEW

**Comment by git-bruh** [comment]
`surf` requires `webkit2gtk`

`icu` required by chromium, and stuff in @dilyn-corner's kiss-kde, chromium  can be made to use bundled icu

`nettle` dep for `gnutls` which is a dep for:
* `emacs`: required by nothing and package has been orphaned by maintainer
*  `msmtp`: required by nothing
*  `glib-networking`: package dropped. required by nothing now, since `webkitgtk2` and friends have been dropped

`libgpg-error`: `gnupg2`

`libXslt`: `chromium` and `qt5{,-webengine}`, chromium can be made to use bundled lib.

that's all

**Comment by dilyn-corner** [comment]
`libgcrypt` needs `libgpg-error`, and is required by `chromium`. 
`libXslt` is not a hard dependency for building `qt5{-webengine}`. 

Do not worry about keeping things in community for KISS-kde; I have elected to simply maintain everything in community that project needs within that project.

**Comment by jedahan** [comment]
You can also remove my packages (I think just `osh`?) as i havent had time to work on them.

I would also love if instead of removing, they got moved to a kiss-graveyard repository to make it easier to search for

**Comment by git-bruh** [comment]
yes @jedahan, we're planning to put these packages into a separate repo.

**Comment by noocsharp** [comment]
Note that `icu` is also a dependency of `libpsl` which is a dependency of `wget`

**Comment by git-bruh** [comment]
I can take over maintainership for `libgpg-error`

PRs are needed for the following, then this PR can be merged:
* `qt5{-webengine}` to use bundled `libXslt`/`icu` @dilyn-corner 
* `msmtp` to use `libtls` @Vouivre

**Comment by dilyn-corner** [comment]
kappa https://github.com/kiss-community/repo-community/pull/93

**Comment by Vouivre** [comment]
I have removed `gnutls` from `msmtp`. For me you can drop `gnutls`.

**Comment by git-bruh** [comment]
@Vouivre Could you drop `emacs` aswell ? No one has taken it up since you orphaned it and it's the last package dependent on `gnutls`

**Comment by Vouivre** [comment]
Yes, no problem. Do you make the change in the `drop` branch ? Or I do it ?

**Comment by git-bruh** [comment]
@Vouivre You can do it directly in `main`

**Comment by Vouivre** [comment]
Done!

**Comment by Neustradamus** [comment]
Can you re-add ppp?

Thanks in advance.

Linked to:
- https://github.com/kisslinux/community/issues/1750
- https://github.com/kiss-community/repo-community/issues/160

**Comment by git-bruh** [comment]
@Neustradamus I don't personally use `ppp` so i won't be able to maintain it, you can send a PR if you want to maintain it.

**Pull request merged**
