### PR TITLE
gnutls: dependency gnutls added

### PR DESCRIPTION
**Pull request by Vouivre**
The missing dependency `pkgconf` has been added. See https://github.com/kiss-community/repo-community/issues/320

Sorry, I forgot to mention that I'm the maintainer. To ease your task, I choosed to close my first PR and to recreate one with
the mention that I'm the maintainer. But github still think it's my first contribution. I don't know why. Probably it's because of my first PR. 

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
This change does not require a relver bump

**Comment by Vouivre** [comment]
You mean version should stay `3.6.15 2` ?

**Comment by dilyn-corner** [comment]
Yes, reason being that 1) if users already have `gnutls` installed, they don't need `pkgconf`, and 2) if they don't have `pkgconf` installed, they would've never built `gnutls`. 
In general, adding a `make` depend wouldn't require a rebuild (primary case would be if `foo` were being built statically, and not including `bar` leaves out features) - since `pkgconf` just acts to help find dependencies, it serves no actual purpose for `gnutls` outside of building it.

**Comment by Vouivre** [comment]
That makes sense, thank you for this explanation! :+1: 
Change done.

**Pull request merged**
