### PR TITLE
gnutls: bumped to 3.6.16

### PR DESCRIPTION
**Pull request by Vouivre**
## Installed manifest of package

(`kiss manifest <pkg>`)

http://pastebin.fr/91611

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by Vouivre** [comment]
Sorry, last time I forgot to update the version number. What's wrong this time ?

**Comment by dilyn-corner** [comment]
You mean the shellcheck failure? that's just because I failed to lint the right files. It's been fixed :)

**Comment by Vouivre** [comment]
Yes, thank you! :+1:

**Comment by wael444** [comment]
@Vouivre , please update gnutls to 3.7.7

**Comment by Vouivre** [comment]
I'll have a look. Next time I would rather use the issue about outdated packages.

**Pull request merged**
