### PR TITLE
meta: update PR template and readme

### PR DESCRIPTION
**Pull request by ArmaanB**
replace k1ss.org links with kiss.armaanb.net, and replace @dylanaraps with @git-bruh

### CODE REVIEW

**Comment by git-bruh** [comment]
I suggest that my username be replaced with "the @kiss-community maintainers"

**Comment by ArmaanB** [comment]
Yeah I was a bit torn on whether to do that or not. I figured that having a single person to mention would be simpler and given that you are the most involved right now, I chose you.

**Comment by ArmaanB** [comment]
Sorry for the force-pushes, I keep forgetting the repo style guide, ironically

**Comment by git-bruh** [comment]
No problem!

**Pull request merged**
