### PR TITLE
cproc: new package

### PR DESCRIPTION
**Pull request by git-bruh**
## Description of package
C11 compiler

## Installed manifest of package

cproc
```
/var/db/kiss/installed/cproc/version
/var/db/kiss/installed/cproc/sources
/var/db/kiss/installed/cproc/manifest
/var/db/kiss/installed/cproc/depends
/var/db/kiss/installed/cproc/build
/var/db/kiss/installed/cproc/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/bin/cproc-qbe
/usr/bin/cproc
/usr/bin/
/usr/
```

qbe:
```
/var/db/kiss/installed/qbe/version
/var/db/kiss/installed/qbe/sources
/var/db/kiss/installed/qbe/manifest
/var/db/kiss/installed/qbe/build
/var/db/kiss/installed/qbe/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/bin/qbe
/usr/bin/
/usr/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

### CODE REVIEW

**Comment by git-bruh** [comment]
Looks like it does not play well with `lld` as `/usr/bin/ld`:
```
ld: error: unable to find library -l:crt1.o
ld: error: unable to find library -l:crti.o
ld: error: unable to find library -lc
ld: error: unable to find library -l:crtn.o
cproc: link: process 13105 exited with status 1
```

**Comment by dilyn-corner** [comment]
That's a bad thing that shouldn't happen, but doesn't happen on Wyverkiss. 🤔

**Comment by git-bruh** [comment]
`--with-ld` specifies the linker called by `cproc` but the arguments remain the same, there aren't any specific rules for different linkers. You can even do `--with-ld=true` which results in empty output.

**Comment by noocsharp** [comment]
I believe you just need to add `-L /lib` to the linker parameters in `config.h`.

**Comment by git-bruh** [comment]
Thanks @noocsharp, that seems to work. I guess GNU `ld` has some default search paths that `lld` doesn't.

**Pull request merged**
