### PR TITLE
[ungoogled]chromium: 91.0.4472.77

### PR DESCRIPTION
**Pull request by git-bruh**
Needs #420, currently building.

### CODE REVIEW

**Comment by git-bruh** [comment]
/var/db/kiss/installed/chromium/version
/var/db/kiss/installed/chromium/sources
/var/db/kiss/installed/chromium/post-install
/var/db/kiss/installed/chromium/patches/musl-v8-monotonic-pthread-cont_timedwait.patch
/var/db/kiss/installed/chromium/patches/musl-sync.patch
/var/db/kiss/installed/chromium/patches/musl-stacktrace.patch
/var/db/kiss/installed/chromium/patches/musl-sandbox.patch
/var/db/kiss/installed/chromium/patches/musl-resolver.patch
/var/db/kiss/installed/chromium/patches/musl-no-mallinfo.patch
/var/db/kiss/installed/chromium/patches/musl-no-getcontext.patch
/var/db/kiss/installed/chromium/patches/musl-no-execinfo.patch
/var/db/kiss/installed/chromium/patches/musl-libc++.patch
/var/db/kiss/installed/chromium/patches/musl-hacks.patch
/var/db/kiss/installed/chromium/patches/musl-fixes.patch
/var/db/kiss/installed/chromium/patches/musl-dns-config.patch
/var/db/kiss/installed/chromium/patches/musl-default-pthread-stacksize.patch
/var/db/kiss/installed/chromium/patches/musl-crashpad.patch
/var/db/kiss/installed/chromium/patches/glibc-malloc.patch
/var/db/kiss/installed/chromium/patches/glibc-2.33.patch
/var/db/kiss/installed/chromium/patches/chromium-sql-make-VirtualCursor-standard-layout-type.patch
/var/db/kiss/installed/chromium/patches/chromium-optional-atk-dbus.patch
/var/db/kiss/installed/chromium/patches/
/var/db/kiss/installed/chromium/manifest
/var/db/kiss/installed/chromium/files/chromium.sh
/var/db/kiss/installed/chromium/files/
/var/db/kiss/installed/chromium/depends
/var/db/kiss/installed/chromium/checksums
/var/db/kiss/installed/chromium/build
/var/db/kiss/installed/chromium/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/lib/chromium/v8_context_snapshot.bin
/usr/lib/chromium/snapshot_blob.bin
/usr/lib/chromium/resources.pak
/usr/lib/chromium/locales/zh-TW.pak
/usr/lib/chromium/locales/zh-CN.pak
/usr/lib/chromium/locales/vi.pak
/usr/lib/chromium/locales/uk.pak
/usr/lib/chromium/locales/tr.pak
/usr/lib/chromium/locales/th.pak
/usr/lib/chromium/locales/te.pak
/usr/lib/chromium/locales/ta.pak
/usr/lib/chromium/locales/sw.pak
/usr/lib/chromium/locales/sv.pak
/usr/lib/chromium/locales/sr.pak
/usr/lib/chromium/locales/sl.pak
/usr/lib/chromium/locales/sk.pak
/usr/lib/chromium/locales/ru.pak
/usr/lib/chromium/locales/ro.pak
/usr/lib/chromium/locales/pt-PT.pak
/usr/lib/chromium/locales/pt-BR.pak
/usr/lib/chromium/locales/pl.pak
/usr/lib/chromium/locales/nl.pak
/usr/lib/chromium/locales/nb.pak
/usr/lib/chromium/locales/ms.pak
/usr/lib/chromium/locales/mr.pak
/usr/lib/chromium/locales/ml.pak
/usr/lib/chromium/locales/lv.pak
/usr/lib/chromium/locales/lt.pak
/usr/lib/chromium/locales/ko.pak
/usr/lib/chromium/locales/kn.pak
/usr/lib/chromium/locales/ja.pak
/usr/lib/chromium/locales/it.pak
/usr/lib/chromium/locales/id.pak
/usr/lib/chromium/locales/hu.pak
/usr/lib/chromium/locales/hr.pak
/usr/lib/chromium/locales/hi.pak
/usr/lib/chromium/locales/he.pak
/usr/lib/chromium/locales/gu.pak
/usr/lib/chromium/locales/fr.pak
/usr/lib/chromium/locales/fil.pak
/usr/lib/chromium/locales/fi.pak
/usr/lib/chromium/locales/fa.pak
/usr/lib/chromium/locales/et.pak
/usr/lib/chromium/locales/es.pak
/usr/lib/chromium/locales/es-419.pak
/usr/lib/chromium/locales/en-US.pak
/usr/lib/chromium/locales/en-GB.pak
/usr/lib/chromium/locales/el.pak
/usr/lib/chromium/locales/de.pak
/usr/lib/chromium/locales/da.pak
/usr/lib/chromium/locales/cs.pak
/usr/lib/chromium/locales/ca.pak
/usr/lib/chromium/locales/bn.pak
/usr/lib/chromium/locales/bg.pak
/usr/lib/chromium/locales/ar.pak
/usr/lib/chromium/locales/am.pak
/usr/lib/chromium/locales/
/usr/lib/chromium/libGLESv2.so
/usr/lib/chromium/libEGL.so
/usr/lib/chromium/icudtl.dat
/usr/lib/chromium/headless_lib.pak
/usr/lib/chromium/chromium
/usr/lib/chromium/chrome_200_percent.pak
/usr/lib/chromium/chrome_100_percent.pak
/usr/lib/chromium/
/usr/lib/
/usr/bin/chromium
/usr/bin/
/usr/

**Comment by dilyn-corner** [comment]
https://github.com/kiss-community/repo-community/blob/1a5a820b435464e7a88ab622217ef9d8cd3bd0bb/community/chromium/build#L126 
https://github.com/kiss-community/repo-community/blob/1a5a820b435464e7a88ab622217ef9d8cd3bd0bb/community/chromium/depends#L2
:thinking:
Also, what's wrong with `libvpx`? Anything specific?

**Comment by git-bruh** [comment]
I don't remember but `use_atk=false` was probably required to drop dbus, it links to it anyways.

For `libvpx` i haven't tested it myself but it's commented out in the arch PKGBUILD, so I'm guessing it often has some breakage like https://github.com/kiss-community/repo-main/commit/2dba4c4889a8ea9a35d6168ca52dc957d8503699#diff-d7da2be2883251bdd3f087e34c92cee6507f37455a867710d55ba1f928631e4dR16�

**Comment by git-bruh** [comment]
Btw shellcheck might be failing because I changed [SC2039](https://github.com/koalaman/shellcheck/wiki/SC2039) to the more recently introduced, and more specific [SC3045](https://github.com/koalaman/shellcheck/wiki/SC3045) as it was failing locally otherwise. Older versions of shellcheck won't recognize it, and newer ones will complain since we're not using the correct  statement.

**Comment by dilyn-corner** [comment]
Explains why MY `shellcheck` complains but our action fails. Darn you, Ubuntu.

**Comment by git-bruh** [comment]
# shellcheck disable=2039,3045

i just realized we could disable them both for the time being..﻿

**Pull request merged**
