### PR TITLE
refind: bumped to 0.13.1

### PR DESCRIPTION
**Pull request by Ominitay**
Updated refind to 0.13.1

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by git-bruh** [comment]
You missed `checksums`

**Comment by Ominitay** [comment]
> You missed `checksums`

Wow I'm an idiot

**Comment by Ominitay** [comment]
That's done

**Comment by git-bruh** [comment]
The `version` file too :p

**Comment by Ominitay** [comment]
I could have sworn I had :woman_facepalming:

**Pull request merged**
