### PR TITLE
i3[-gaps]: added missing dependencies and bumped to 4.19.1

### PR DESCRIPTION
**Pull request by Ominitay**
Please fill out the template.

Read: https://k1ss.org/wiki/kiss/style-guide

---

## Installed manifest of package

```
~ $ kiss manifest i3[-gaps]
/var/db/kiss/installed/i3[-gaps]/version
/var/db/kiss/installed/i3[-gaps]/sources
/var/db/kiss/installed/i3[-gaps]/patches/i3-no-libstartup-notification.patch
/var/db/kiss/installed/i3[-gaps]/patches/
/var/db/kiss/installed/i3[-gaps]/manifest
/var/db/kiss/installed/i3[-gaps]/etcsums
/var/db/kiss/installed/i3[-gaps]/depends
/var/db/kiss/installed/i3[-gaps]/checksums
/var/db/kiss/installed/i3[-gaps]/build
/var/db/kiss/installed/i3[-gaps]/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/xsessions/i3.desktop
/usr/share/xsessions/i3-with-shmlog.desktop
/usr/share/xsessions/
/usr/share/doc/i3/wsbar.png
/usr/share/doc/i3/two_terminals.png
/usr/share/doc/i3/two_columns.png
/usr/share/doc/i3/tree-shot4.png
/usr/share/doc/i3/tree-shot3.png
/usr/share/doc/i3/tree-shot2.png
/usr/share/doc/i3/tree-shot1.png
/usr/share/doc/i3/tree-layout2.png
/usr/share/doc/i3/tree-layout1.png
/usr/share/doc/i3/snapping.png
/usr/share/doc/i3/single_terminal.png
/usr/share/doc/i3/refcard_style.css
/usr/share/doc/i3/refcard.html
/usr/share/doc/i3/modes.png
/usr/share/doc/i3/logo-30.png
/usr/share/doc/i3/layout-saving-1.png
/usr/share/doc/i3/keyboard-layer2.png
/usr/share/doc/i3/keyboard-layer1.png
/usr/share/doc/i3/i3-sync.png
/usr/share/doc/i3/i3-sync-working.png
/usr/share/doc/i3/bigpicture.png
/usr/share/doc/i3/
/usr/share/doc/
/usr/share/applications/i3.desktop
/usr/share/applications/
/usr/share/
/usr/include/i3/ipc.h
/usr/include/i3/
/usr/include/
/usr/bin/i3bar
/usr/bin/i3-with-shmlog
/usr/bin/i3-sensible-terminal
/usr/bin/i3-sensible-pager
/usr/bin/i3-sensible-editor
/usr/bin/i3-save-tree
/usr/bin/i3-nagbar
/usr/bin/i3-msg
/usr/bin/i3-migrate-config-to-v4
/usr/bin/i3-input
/usr/bin/i3-dump-log
/usr/bin/i3-dmenu-desktop
/usr/bin/i3-config-wizard
/usr/bin/i3
/usr/bin/
/usr/
/etc/i3/config.keycodes
/etc/i3/config
/etc/i3/
/etc/
```

## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by git-bruh** [comment]
Why is `bash` a dependency ?

**Comment by Ominitay** [comment]
> Why is `bash` a dependency ?

It needs bash in order to build.

**Comment by git-bruh** [comment]
It's a `meson` project no? Why would it need `bash` to build 🤔
+ build dependencies should be marked as `make`, so you'd put `bash make` in the `depends` file

Also, you should confirm whether it needs `bash` or not because i don't see it mentioned as a make dependency on the Arch package, Though `bash` is a make dep for few other packages

**Comment by Ominitay** [comment]
> It's a `meson` project no? Why would it need `bash` to build 
> 
> * build dependencies should be marked as `make`, so you'd put `bash make` in the `depends` file
> 
> Also, you should confirm whether it needs `bash` or not because i don't see it mentioned as a make dependency on the Arch package, Though `bash` is a make dep for few other packages

I was building it in a VM, and I got an error that bash was required when building. I didn't know about marking build-time dependencies as `make`, so I'll go through and change that when I can. Would this indicate that it is not required at runtime though?

**Comment by git-bruh** [comment]
Yeah, `bash make` means that the dep can be discarded from the system after installing the package

**Pull request merged**
