### PR TITLE
brownout: new package at 0.4

### PR DESCRIPTION
**Pull request by lowercasename**
## Description of package

A scriptable, minimal f.lux/redshift alternative which only depends on libX11

## Installed manifest of package

```
/var/db/kiss/installed/brownout/version
/var/db/kiss/installed/brownout/sources
/var/db/kiss/installed/brownout/manifest
/var/db/kiss/installed/brownout/depends
/var/db/kiss/installed/brownout/dependencies
/var/db/kiss/installed/brownout/build
/var/db/kiss/installed/brownout/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/man/man1/brownout.1
/usr/share/man/man1/
/usr/share/man/
/usr/share/
/usr/bin/is-day
/usr/bin/brownout
/usr/bin/
/usr/
```

## New package

- [X] Latest upstream version.
- [X] I agree to maintain this package.
- [X] I agree to notify the @kiss-community maintainers if I can no longer maintain this package.

### CODE REVIEW

**Comment by git-bruh** [comment]
The `dependencies` file should be renamed to `depends`, the package manager only reads `depends`.

**Comment by lowercasename** [comment]
Whoops! Thank you!

**Comment by git-bruh** [comment]
Also you should use the [tarball source](https://github.com/graupe/brownout/archive/refs/tags/v0.4.tar.gz) instead of git for this package since the tarball is up to date already (Last commit was made on the same day as the last release)

**Comment by lowercasename** [comment]
Looks good with the tar source :)

**Comment by dilyn-corner** [comment]
This PR also includes your `berry` commit. Can you rebase onto remote/main and force push your changes?

**Comment by lowercasename** [comment]
Did that do it? Sorry, I seem to be forever getting to grips with GitHub!

**Comment by dilyn-corner** [comment]
That did do it! 
`git` is a complicated beast. Only reason I knew how to solve it is I've had to do it before...

**Pull request merged**
