### PR TITLE
exiftool: bumped to 12.20

### PR DESCRIPTION
**Pull request by Vouivre**
## Existing package

- [x] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
Mmm. @Vouivre next time please include the manifest :)

**Comment by Vouivre** [comment]
@dilyn-corner Because this package doesn't exist on kisslinux/community ?

**Comment by dilyn-corner** [comment]
Just as proof that you built and installed it

**Comment by dilyn-corner** [comment]
For changes like dependencies or formatting the manifest is unecessary but I'd think of version changes like new packages. 

I didn't think about it until after I had merged both and I figured you'd only need to hear it once :) 

Thank you!

**Pull request merged**
