### PR TITLE
protobuf: bump to version 3.17.0

### PR DESCRIPTION
**Pull request by jslick**
Dependents (mosh) will need rebuild

## Installed manifest of package

```
/var/db/kiss/installed/protobuf/version
/var/db/kiss/installed/protobuf/sources
/var/db/kiss/installed/protobuf/manifest
/var/db/kiss/installed/protobuf/checksums
/var/db/kiss/installed/protobuf/build
/var/db/kiss/installed/protobuf/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/vim/vimfiles/syntax/proto.vim
/usr/share/vim/vimfiles/syntax/
/usr/share/vim/vimfiles/
/usr/share/vim/
/usr/share/
/usr/lib/pkgconfig/protobuf.pc
/usr/lib/pkgconfig/protobuf-lite.pc
/usr/lib/pkgconfig/
/usr/lib/libprotoc.so.28.0.0
/usr/lib/libprotoc.so.28
/usr/lib/libprotoc.so
/usr/lib/libprotoc.a
/usr/lib/libprotobuf.so.28.0.0
/usr/lib/libprotobuf.so.28
/usr/lib/libprotobuf.so
/usr/lib/libprotobuf.a
/usr/lib/libprotobuf-lite.so.28.0.0
/usr/lib/libprotobuf-lite.so.28
/usr/lib/libprotobuf-lite.so
/usr/lib/libprotobuf-lite.a
/usr/lib/
/usr/include/google/protobuf/wrappers.proto
/usr/include/google/protobuf/wrappers.pb.h
/usr/include/google/protobuf/wire_format_lite.h
/usr/include/google/protobuf/wire_format.h
/usr/include/google/protobuf/util/type_resolver_util.h
/usr/include/google/protobuf/util/type_resolver.h
/usr/include/google/protobuf/util/time_util.h
/usr/include/google/protobuf/util/message_differencer.h
/usr/include/google/protobuf/util/json_util.h
/usr/include/google/protobuf/util/field_mask_util.h
/usr/include/google/protobuf/util/field_comparator.h
/usr/include/google/protobuf/util/delimited_message_util.h
/usr/include/google/protobuf/util/
/usr/include/google/protobuf/unknown_field_set.h
/usr/include/google/protobuf/type.proto
/usr/include/google/protobuf/type.pb.h
/usr/include/google/protobuf/timestamp.proto
/usr/include/google/protobuf/timestamp.pb.h
/usr/include/google/protobuf/text_format.h
/usr/include/google/protobuf/stubs/template_util.h
/usr/include/google/protobuf/stubs/strutil.h
/usr/include/google/protobuf/stubs/stringpiece.h
/usr/include/google/protobuf/stubs/stl_util.h
/usr/include/google/protobuf/stubs/status.h
/usr/include/google/protobuf/stubs/port.h
/usr/include/google/protobuf/stubs/platform_macros.h
/usr/include/google/protobuf/stubs/once.h
/usr/include/google/protobuf/stubs/mutex.h
/usr/include/google/protobuf/stubs/map_util.h
/usr/include/google/protobuf/stubs/macros.h
/usr/include/google/protobuf/stubs/logging.h
/usr/include/google/protobuf/stubs/hash.h
/usr/include/google/protobuf/stubs/common.h
/usr/include/google/protobuf/stubs/casts.h
/usr/include/google/protobuf/stubs/callback.h
/usr/include/google/protobuf/stubs/bytestream.h
/usr/include/google/protobuf/stubs/
/usr/include/google/protobuf/struct.proto
/usr/include/google/protobuf/struct.pb.h
/usr/include/google/protobuf/source_context.proto
/usr/include/google/protobuf/source_context.pb.h
/usr/include/google/protobuf/service.h
/usr/include/google/protobuf/repeated_field.h
/usr/include/google/protobuf/reflection_ops.h
/usr/include/google/protobuf/reflection.h
/usr/include/google/protobuf/port_undef.inc
/usr/include/google/protobuf/port_def.inc
/usr/include/google/protobuf/port.h
/usr/include/google/protobuf/parse_context.h
/usr/include/google/protobuf/metadata_lite.h
/usr/include/google/protobuf/metadata.h
/usr/include/google/protobuf/message_lite.h
/usr/include/google/protobuf/message.h
/usr/include/google/protobuf/map_type_handler.h
/usr/include/google/protobuf/map_field_lite.h
/usr/include/google/protobuf/map_field_inl.h
/usr/include/google/protobuf/map_field.h
/usr/include/google/protobuf/map_entry_lite.h
/usr/include/google/protobuf/map_entry.h
/usr/include/google/protobuf/map.h
/usr/include/google/protobuf/io/zero_copy_stream_impl_lite.h
/usr/include/google/protobuf/io/zero_copy_stream_impl.h
/usr/include/google/protobuf/io/zero_copy_stream.h
/usr/include/google/protobuf/io/tokenizer.h
/usr/include/google/protobuf/io/strtod.h
/usr/include/google/protobuf/io/printer.h
/usr/include/google/protobuf/io/io_win32.h
/usr/include/google/protobuf/io/gzip_stream.h
/usr/include/google/protobuf/io/coded_stream.h
/usr/include/google/protobuf/io/
/usr/include/google/protobuf/implicit_weak_message.h
/usr/include/google/protobuf/has_bits.h
/usr/include/google/protobuf/generated_message_util.h
/usr/include/google/protobuf/generated_message_table_driven.h
/usr/include/google/protobuf/generated_message_reflection.h
/usr/include/google/protobuf/generated_enum_util.h
/usr/include/google/protobuf/generated_enum_reflection.h
/usr/include/google/protobuf/field_mask.proto
/usr/include/google/protobuf/field_mask.pb.h
/usr/include/google/protobuf/extension_set_inl.h
/usr/include/google/protobuf/extension_set.h
/usr/include/google/protobuf/empty.proto
/usr/include/google/protobuf/empty.pb.h
/usr/include/google/protobuf/dynamic_message.h
/usr/include/google/protobuf/duration.proto
/usr/include/google/protobuf/duration.pb.h
/usr/include/google/protobuf/descriptor_database.h
/usr/include/google/protobuf/descriptor.proto
/usr/include/google/protobuf/descriptor.pb.h
/usr/include/google/protobuf/descriptor.h
/usr/include/google/protobuf/compiler/ruby/ruby_generator.h
/usr/include/google/protobuf/compiler/ruby/
/usr/include/google/protobuf/compiler/python/python_generator.h
/usr/include/google/protobuf/compiler/python/
/usr/include/google/protobuf/compiler/plugin.proto
/usr/include/google/protobuf/compiler/plugin.pb.h
/usr/include/google/protobuf/compiler/plugin.h
/usr/include/google/protobuf/compiler/php/php_generator.h
/usr/include/google/protobuf/compiler/php/
/usr/include/google/protobuf/compiler/parser.h
/usr/include/google/protobuf/compiler/objectivec/objectivec_helpers.h
/usr/include/google/protobuf/compiler/objectivec/objectivec_generator.h
/usr/include/google/protobuf/compiler/objectivec/
/usr/include/google/protobuf/compiler/js/well_known_types_embed.h
/usr/include/google/protobuf/compiler/js/js_generator.h
/usr/include/google/protobuf/compiler/js/
/usr/include/google/protobuf/compiler/java/java_names.h
/usr/include/google/protobuf/compiler/java/java_kotlin_generator.h
/usr/include/google/protobuf/compiler/java/java_generator.h
/usr/include/google/protobuf/compiler/java/
/usr/include/google/protobuf/compiler/importer.h
/usr/include/google/protobuf/compiler/csharp/csharp_names.h
/usr/include/google/protobuf/compiler/csharp/csharp_generator.h
/usr/include/google/protobuf/compiler/csharp/
/usr/include/google/protobuf/compiler/cpp/cpp_generator.h
/usr/include/google/protobuf/compiler/cpp/
/usr/include/google/protobuf/compiler/command_line_interface.h
/usr/include/google/protobuf/compiler/code_generator.h
/usr/include/google/protobuf/compiler/
/usr/include/google/protobuf/arenastring.h
/usr/include/google/protobuf/arena_impl.h
/usr/include/google/protobuf/arena.h
/usr/include/google/protobuf/api.proto
/usr/include/google/protobuf/api.pb.h
/usr/include/google/protobuf/any.proto
/usr/include/google/protobuf/any.pb.h
/usr/include/google/protobuf/any.h
/usr/include/google/protobuf/
/usr/include/google/
/usr/include/
/usr/bin/protoc
/usr/bin/
/usr/
```

## Existing package

- [X] I am the maintainer of this package.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
I assume similarly for `android-tools` @git-bruh -- can each of you also bump the relver, respectively?

**Comment by jslick** [comment]
Oh, so, the same as true for the previous bump.  oops.

> I assume similarly for `android-tools` @git-bruh -- can each of you also bump the relver, respectively?

Does android-tools use a solib or just invoke the protobuf compiler (protoc)?  If it only uses protoc, it should be fine w/o a rebuild.

**Comment by git-bruh** [comment]
build seems to be failing, probably due to gcc 11. I'll bump it once i figure out the failure.

**Comment by sdsddsd1** [comment]
@git-bruh : I have just build protobuf from kiss-games which is identical with gcc11. Builds fine for me.
https://github.com/sdsddsd1/kiss-games/blob/master/equipment/protobuf/build

**Comment by git-bruh** [comment]
Sorry i meant `android-tools`, was commenting from github cli and it tried to evaluate "android-tools" in a subshell

**Comment by jslick** [comment]
I added bump mosh relver commit

**Pull request merged**
