### PR TITLE
refind: new package at 0.12.0

### PR DESCRIPTION
**Pull request by Ominitay**
## Description of package
rEFInd is a graphical boot manager.

## Installed manifest of package

(`kiss manifest refind`)

```
/var/db/kiss/installed/refind/version
/var/db/kiss/installed/refind/sources
/var/db/kiss/installed/refind/patches/gcc10-fix.patch
/var/db/kiss/installed/refind/patches/force-inline-musl.patch
/var/db/kiss/installed/refind/patches/
/var/db/kiss/installed/refind/manifest
/var/db/kiss/installed/refind/etcsums
/var/db/kiss/installed/refind/depends
/var/db/kiss/installed/refind/checksums
/var/db/kiss/installed/refind/build
/var/db/kiss/installed/refind/
/var/db/kiss/installed/
/var/db/kiss/
/var/db/
/var/
/usr/share/refind/tools_x64/gptsync_x64.efi
/usr/share/refind/tools_x64/
/usr/share/refind/refind_x64.efi
/usr/share/refind/refind.conf-sample
/usr/share/refind/icons/vol_optical.png
/usr/share/refind/icons/vol_net.png
/usr/share/refind/icons/vol_internal.png
/usr/share/refind/icons/vol_external.png
/usr/share/refind/icons/transparent.png
/usr/share/refind/icons/tool_windows_rescue.png
/usr/share/refind/icons/tool_shell.png
/usr/share/refind/icons/tool_rescue.png
/usr/share/refind/icons/tool_part.png
/usr/share/refind/icons/tool_netboot.png
/usr/share/refind/icons/tool_mok_tool.png
/usr/share/refind/icons/tool_memtest.png
/usr/share/refind/icons/tool_fwupdate.png
/usr/share/refind/icons/tool_apple_rescue.png
/usr/share/refind/icons/svg/tool_rescue.svg
/usr/share/refind/icons/svg/tool_memtest.svg
/usr/share/refind/icons/svg/tool_fwupdate.svg
/usr/share/refind/icons/svg/os_xenial.svg
/usr/share/refind/icons/svg/os_win.svg
/usr/share/refind/icons/svg/os_refit.svg
/usr/share/refind/icons/svg/os_refind.svg
/usr/share/refind/icons/svg/os_redhat.svg
/usr/share/refind/icons/svg/os_netbsd.svg
/usr/share/refind/icons/svg/os_mac.svg
/usr/share/refind/icons/svg/os_legacy.svg
/usr/share/refind/icons/svg/os_haiku.svg
/usr/share/refind/icons/svg/os_gummiboot.svg
/usr/share/refind/icons/svg/os_elementary.svg
/usr/share/refind/icons/svg/os_devuan.svg
/usr/share/refind/icons/svg/os_debian.svg
/usr/share/refind/icons/svg/os_clover.svg
/usr/share/refind/icons/svg/mouse.svg
/usr/share/refind/icons/svg/func_csr_rotate.svg
/usr/share/refind/icons/svg/boot_win.svg
/usr/share/refind/icons/svg/
/usr/share/refind/icons/os_zesty.png
/usr/share/refind/icons/os_xubuntu.png
/usr/share/refind/icons/os_xenial.png
/usr/share/refind/icons/os_win8.png
/usr/share/refind/icons/os_win.png
/usr/share/refind/icons/os_void.png
/usr/share/refind/icons/os_unknown.png
/usr/share/refind/icons/os_ubuntu.png
/usr/share/refind/icons/os_trusty.png
/usr/share/refind/icons/os_systemd.png
/usr/share/refind/icons/os_suse.png
/usr/share/refind/icons/os_slackware.png
/usr/share/refind/icons/os_refit.png
/usr/share/refind/icons/os_refind.png
/usr/share/refind/icons/os_redhat.png
/usr/share/refind/icons/os_opensuse.png
/usr/share/refind/icons/os_network.png
/usr/share/refind/icons/os_netbsd.png
/usr/share/refind/icons/os_mandriva.png
/usr/share/refind/icons/os_mageia.png
/usr/share/refind/icons/os_mac.png
/usr/share/refind/icons/os_lubuntu.png
/usr/share/refind/icons/os_linuxmint.png
/usr/share/refind/icons/os_linux.png
/usr/share/refind/icons/os_legacy.png
/usr/share/refind/icons/os_kubuntu.png
/usr/share/refind/icons/os_hwtest.png
/usr/share/refind/icons/os_haiku.png
/usr/share/refind/icons/os_gummiboot.png
/usr/share/refind/icons/os_gentoo.png
/usr/share/refind/icons/os_frugalware.png
/usr/share/refind/icons/os_freebsd.png
/usr/share/refind/icons/os_fedora.png
/usr/share/refind/icons/os_elementary.png
/usr/share/refind/icons/os_devuan.png
/usr/share/refind/icons/os_debian.png
/usr/share/refind/icons/os_crunchbang.png
/usr/share/refind/icons/os_clover.png
/usr/share/refind/icons/os_chrome.png
/usr/share/refind/icons/os_chakra.png
/usr/share/refind/icons/os_centos.png
/usr/share/refind/icons/os_bionic.png
/usr/share/refind/icons/os_artful.png
/usr/share/refind/icons/os_arch.png
/usr/share/refind/icons/mouse.png
/usr/share/refind/icons/func_shutdown.png
/usr/share/refind/icons/func_reset.png
/usr/share/refind/icons/func_install.png
/usr/share/refind/icons/func_hidden.png
/usr/share/refind/icons/func_firmware.png
/usr/share/refind/icons/func_exit.png
/usr/share/refind/icons/func_csr_rotate.png
/usr/share/refind/icons/func_bootorder.png
/usr/share/refind/icons/func_about.png
/usr/share/refind/icons/boot_win.png
/usr/share/refind/icons/boot_linux.png
/usr/share/refind/icons/arrow_right.png
/usr/share/refind/icons/arrow_left.png
/usr/share/refind/icons/
/usr/share/refind/fonts/ubuntu-mono-28.png
/usr/share/refind/fonts/ubuntu-mono-24.png
/usr/share/refind/fonts/ubuntu-mono-16.png
/usr/share/refind/fonts/ubuntu-mono-14.png
/usr/share/refind/fonts/ubuntu-mono-12.png
/usr/share/refind/fonts/nimbus-mono-28.png
/usr/share/refind/fonts/nimbus-mono-24.png
/usr/share/refind/fonts/nimbus-mono-16.png
/usr/share/refind/fonts/nimbus-mono-14.png
/usr/share/refind/fonts/nimbus-mono-12.png
/usr/share/refind/fonts/liberation-mono-regular-28.png
/usr/share/refind/fonts/liberation-mono-regular-24.png
/usr/share/refind/fonts/liberation-mono-regular-14.png
/usr/share/refind/fonts/liberation-mono-regular-12.png
/usr/share/refind/fonts/
/usr/share/refind/drivers_x64/reiserfs_x64.efi
/usr/share/refind/drivers_x64/iso9660_x64.efi
/usr/share/refind/drivers_x64/hfs_x64.efi
/usr/share/refind/drivers_x64/ext4_x64.efi
/usr/share/refind/drivers_x64/ext2_x64.efi
/usr/share/refind/drivers_x64/btrfs_x64.efi
/usr/share/refind/drivers_x64/
/usr/share/refind/
/usr/share/man/man8/refind-mkdefault.8
/usr/share/man/man8/refind-install.8
/usr/share/man/man8/mvrefind.8
/usr/share/man/man8/mkrlconf.8
/usr/share/man/man8/
/usr/share/man/
/usr/share/licenses/refind/LICENSE.txt
/usr/share/licenses/refind/
/usr/share/licenses/
/usr/share/doc/refind/html/yosemite.html
/usr/share/doc/refind/html/windows8-on-mac-efi.txt
/usr/share/doc/refind/html/windows-gpt.png
/usr/share/doc/refind/html/using.html
/usr/share/doc/refind/html/tux-refind-theme.png
/usr/share/doc/refind/html/todo.html
/usr/share/doc/refind/html/themes.html
/usr/share/doc/refind/html/submenu.png
/usr/share/doc/refind/html/styles.css
/usr/share/doc/refind/html/startup-disk.png
/usr/share/doc/refind/html/sip.html
/usr/share/doc/refind/html/secureboot.html
/usr/share/doc/refind/html/revisions.html
/usr/share/doc/refind/html/refind.png
/usr/share/doc/refind/html/refind-mkdefault.html
/usr/share/doc/refind/html/refind-install.html
/usr/share/doc/refind/html/refind-background.png
/usr/share/doc/refind/html/refind-background-snowy.png
/usr/share/doc/refind/html/rEFInd-Metro.png
/usr/share/doc/refind/html/os_legacy.png
/usr/share/doc/refind/html/mvrefind.html
/usr/share/doc/refind/html/msinfo32.png
/usr/share/doc/refind/html/mkrlconf.html
/usr/share/doc/refind/html/manual-submenu.png
/usr/share/doc/refind/html/mac-theme.png
/usr/share/doc/refind/html/linux.html
/usr/share/doc/refind/html/installing.html
/usr/share/doc/refind/html/install.png
/usr/share/doc/refind/html/index.html
/usr/share/doc/refind/html/getting.html
/usr/share/doc/refind/html/func_install.png
/usr/share/doc/refind/html/func_csr_rotate.png
/usr/share/doc/refind/html/func_bootorder.png
/usr/share/doc/refind/html/features.html
/usr/share/doc/refind/html/editor.png
/usr/share/doc/refind/html/easyuefi.png
/usr/share/doc/refind/html/drivers.html
/usr/share/doc/refind/html/donate.svg
/usr/share/doc/refind/html/donate.png
/usr/share/doc/refind/html/configfile.html
/usr/share/doc/refind/html/bootorder.png
/usr/share/doc/refind/html/bootmode.html
/usr/share/doc/refind/html/bootcoup.html
/usr/share/doc/refind/html/automatic-submenu.png
/usr/share/doc/refind/html/ambience.png
/usr/share/doc/refind/html/about.svg
/usr/share/doc/refind/html/about.png
/usr/share/doc/refind/html/MokManager2.png
/usr/share/doc/refind/html/MokManager1.png
/usr/share/doc/refind/html/HashTool2.png
/usr/share/doc/refind/html/HashTool1.png
/usr/share/doc/refind/html/FDL-1.3.txt
/usr/share/doc/refind/html/
/usr/share/doc/refind/README.txt
/usr/share/doc/refind/README.refind-mkfont.txt
/usr/share/doc/refind/README.keys.txt
/usr/share/doc/refind/README.icons.txt
/usr/share/doc/refind/NEWS.txt
/usr/share/doc/refind/CREDITS.txt
/usr/share/doc/refind/
/usr/share/doc/
/usr/share/
/usr/bin/refind-mkfont
/usr/bin/refind-mkdefault
/usr/bin/refind-install
/usr/bin/mvrefind
/usr/bin/mkrlconf
/usr/bin/
/usr/
/etc/refind.d/keys/refind.crt
/etc/refind.d/keys/refind.cer
/etc/refind.d/keys/openSUSE-UEFI-CA-Certificate.crt
/etc/refind.d/keys/openSUSE-UEFI-CA-Certificate.cer
/etc/refind.d/keys/openSUSE-UEFI-CA-Certificate-4096.crt
/etc/refind.d/keys/openSUSE-UEFI-CA-Certificate-4096.cer
/etc/refind.d/keys/microsoft-uefica-public.crt
/etc/refind.d/keys/microsoft-uefica-public.cer
/etc/refind.d/keys/microsoft-pca-public.cer
/etc/refind.d/keys/microsoft-kekca-public.cer
/etc/refind.d/keys/fedora-ca.crt
/etc/refind.d/keys/fedora-ca.cer
/etc/refind.d/keys/centos.crt
/etc/refind.d/keys/centos.cer
/etc/refind.d/keys/canonical-uefi-ca.crt
/etc/refind.d/keys/canonical-uefi-ca.cer
/etc/refind.d/keys/altlinux.cer
/etc/refind.d/keys/SLES-UEFI-CA-Certificate.crt
/etc/refind.d/keys/SLES-UEFI-CA-Certificate.cer
/etc/refind.d/keys/
/etc/refind.d/
/etc/
```

## New package

- [x] Latest upstream version.
- [x] I agree to maintain this package.
- [x] I agree to notify @dylanaraps if I can no longer maintain this package.

### CODE REVIEW

**Comment by Ominitay** [comment]
Depends on #105

**Comment by noocsharp** [comment]
Are you sure about the gnu-efi dependency? I remember installing refind with it a few months ago.

**Comment by Ominitay** [comment]
> Are you sure about the gnu-efi dependency? I remember installing refind with it a few months ago.

GNU-EFI is a build-time dependency. You must use either that or TianoCore EDK2 to build it.

**Comment by Ominitay** [comment]
Also to the repo maintainers: I need to fix the mistakes I made with the build script -- I'll have that done soon.

**Comment by Ominitay** [comment]
Should be ready for merge now

**Comment by git-bruh** [comment]
Both the patches can be replaced with `sed` calls, could you do that ?

**Comment by git-bruh** [comment]
`sed -i 's/__always_inline/inline __attribute__((__always_inline__))/g' filesystems/zstd/fse_decompress.c filesystems/zstd/huf_decompress.c filesystems/zstd/zstd_internal.h`

`sed -i 's/-fno-strict-aliasing/& -fno-tree-loop-distribute-patterns/' Make.common`

**Comment by git-bruh** [comment]
Also, you should get rid of the `-v` flag in all the `install` command and also drop the LICENSE because I don't think licenses are installed in any KISS package

**Comment by Ominitay** [comment]
> `sed -i 's/__always_inline/inline __attribute__((__always_inline__))/g' filesystems/zstd/fse_decompress.c filesystems/zstd/huf_decompress.c filesystems/zstd/zstd_internal.h`
> 
> `sed -i 's/-fno-strict-aliasing/& -fno-tree-loop-distribute-patterns/' Make.common`

Done that

**Comment by Ominitay** [comment]
> Also, you should get rid of the `-v` flag in all the `install` commands and drop the LICENSE because I don't think licenses are installed in any KISS package + a simple shell `for` loop can be used for installing the scripts and the docs

I would have thought licenses should be kept with a package, but I'll remove them.

**Comment by Ominitay** [comment]
Also @git-bruh, with POSIX's lack of arrays, how would I construct such a for loop?

**Comment by git-bruh** [comment]
```
# Scripts
for script in refind-install refind-mkdefault mkrlconf mvrefind; do
    install -Dm755 "$script" -t "$1/usr/bin"
done

install -Dm755 fonts/mkfont.sh "$1/usr/bin/refind-mkfont"

# Man pages
install -Dm644 docs/man/*.8 -t "$1/usr/share/man/man8"

# Docs
for doc in CREDITS NEWS README; do
    install -Dm644 "$doc.txt" -t "$1/usr/share/doc/refind"
done

install -Dm644 fonts/README.txt "$1/usr/share/doc/refind/README.refind-mkfont.txt"
install -Dm644 icons/README     "$1/usr/share/doc/refind/README.icons.txt"
install -Dm644 keys/README.txt  "$1/usr/share/doc/refind/README.keys.txt"

for doc in html png svg txt; do
    install -Dm644 "docs/refind/"*.$doc -t "$1/usr/share/doc/refind/html"
done

install -Dm644 docs/Styles/*.css    -t "$1/usr/share/doc/refind/html"
```

I think you shouldn't install the html docs (i doubt anyone would read them) but it doesn't really matter

**Comment by Ominitay** [comment]
Should be ready to merge now!

**Comment by git-bruh** [comment]
thanks

**Pull request merged**
